version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=INSIDE://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"     # For containers like Kafka Connect
      - "19092:19092"   # For host access (KafkaJS on your Mac)
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  

volumes:
  redis-data:
  redpanda-data:
